language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

env:
  global:
    # CRATES_IO_TOKEN=...
    - secure: "FYoav+St+90i6AQzyMw+NJdtktG2UMK7szt7ar88ww7bkkCd9I9qgtqqW6mopzpnguRhBusxoCsmiroFbXVO1R3vSP1ugECUTDCK7x/Tqkc/wa0MOqlmBneG+bZOF3YjiDTfaAIUI8r10RstfRhRwIKgZI3vE/8TEgTGlWW+cZuHaz7U4wesHUY+euuSoLuD7XrlI1N9EBAbHwTtLpfHoONSw8fxVQc0nQ7vTBrC+UQiRZA8oFP7qpJ/9xfsCMWSyVihuSzdHoCRIxCs+rWROBpULAqvPa0vYdxE7oQHPwbaQ8bsv088Mowjaq5Dp8NimodimQsx7D58g/e+INEk9q3dwj/RN0iMgNYqhYv9Wu+vMWNMbvReSHlJtIYWtl2varXQI2hOPC/+6OhfzlAT1hBsrkJjZ6bQ9Yv9NUGNQHNrFvdCKOEvSG3wHNB10mfBB/KSVzB/ya8suEBR07CjzbrzTlH2SUYfSHS5iNbP791kAYp2MyMn69ZajeEZ3iYwwG2lHH2CONB/QiAX6ZDc5J3jM8gmxu2S5QkZkZieBnDZG/OsYjOw7Zka3ktlGW+Khn3RRRsDYMrpAN5qmiEO6vdDP/XcRZw4ERfHQd8A9kEhnhJGOlg6KGyNM0pi7s4IX8VWkbxAmY53HqsyK1eagIVLsxkzCn3GKfVQuufHBBc="

install:
  - pip install 'ghp-import' --user

script:
  - cargo build -v && cargo test -v

before_deploy:
  # Set up credentials for deploying
  # Decrypt GitHub deploy SSH key
  - mkdir -p ${HOME}/.ssh && touch ${HOME}/.ssh/deploy_key && chmod 0600 ${HOME}/.ssh/deploy_key
  - openssl aes-256-cbc -K $encrypted_47ef09588713_key -iv $encrypted_47ef09588713_iv -in ci/deploy_key.enc -out ${HOME}/.ssh/deploy_key -d
  # Make SSH aware of key
  - echo -e "Host github.com\n  IdentityFile ${HOME}/.ssh/deploy_key" >> ${HOME}/.ssh/config
  # Make git push via SSH
  - git remote set-url origin git@github.com:bsteinb/accurate.git
  # Login to cates.io
  - cargo login -v "${CRATES_IO_TOKEN}"
  # Build crate
  - cargo package -v

deploy:
  # Build and upload documentation to GitHub pages
  - provider: script
    script: ci/deploy-docs.sh
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_RUST_VERSION} = stable"
  # Deploy the crate to crates.io
  - provider: script
    script: ci/deploy-crate.sh
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_RUST_VERSION} = stable"
  # Deploy crate to GitHub releases
  - provider: releases
    api_key:
      secure: W1xFNaabWUDugVZIVVlfsw5XX9z+eDt3TI43OkQwftlOd1aZLBRa2Bb3WB6hrfSS+aRaRkzOLybYWJSR7e9yXwe2ClKB78Kfs2IhbxXtfw7f73dBBGRJKpF4vLgQ3hbzw0Zoq2VlQB1BgZNGAb3IxC9YHeEooLzhxFmfmqB68DPtSsgCW664X1EK7cmKrz6q/FqY9roPrfDjwXHuYROtXSB7axSoZFGPkS3kNSGKj04+/ZEKxrUdG+aAL03aHuxcWXu5RBnpREwYMoNbTcBdxv/hIVM9nxBAw1SUEXldJ6v3JuPDdutTy3NNV6zBdZR9yfpBrEbdDtvfpyStTso/0CDiHawpotKKpfEWChuz0rxsiGPVGKWICPHn5YcIMLD4DnfLjXE7cyyKS8ca9sfJbUb+2BvCdF87yiQ5PflaLgvMx5hb+tu2joCrzvVFE8T2xmipi9ka/n348mF1Vvlkz6gMnBX4ZznJpK5KJIPSPfcr2tQp+yFEUVJnnfBYWr8wT+Z76Z1Qd0XddDwKCr/2jJmj52SO/JeqNB8nbmsu1csyCRvda8+TDSMEOzKq96ajQ6jgTvXPb3S8k/2yTjyNBgL7mwvTXBcrVL0lfzmcMTZdC4a9evtPCZytziww2aA08SLWae8OTrtitn4xiiLUNeShpj6D2M23NdL6BB6CUQA=
    file: target/package/accurate-${TRAVIS_TAG}.crate
    skip_cleanup: true
    on:
      repo: bsteinb/accurate
      tags: true
      condition: "${TRAVIS_RUST_VERSION} = stable"
